"""empty message

Revision ID: 1a6d39b190ea
Revises: fb9a770a745b
Create Date: 2020-01-10 20:12:10.087982

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a6d39b190ea'
down_revision = 'fb9a770a745b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habitante_v1', 'cpf',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(collation='utf8_bin', length=11),
               existing_nullable=True)
    op.alter_column('empresa_v1', 'cnpj',
               existing_type=sa.String(length=14),
               type_=mysql.VARCHAR(collation='utf8_bin', length=14),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habitante_v1', 'cpf',
               existing_type=sa.String(length=14),
               type_=mysql.VARCHAR(collation='utf8_bin', length=11),
               existing_nullable=True)
    op.alter_column('empresa_v1', 'cnpj',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(collation='utf8_bin', length=14),
               existing_nullable=True)
    # ### end Alembic commands ###

