"""empty message

Revision ID: 400ee765e679
Revises: 1a6d39b190ea
Create Date: 2020-01-10 23:17:35.513935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '400ee765e679'
down_revision = '1a6d39b190ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresa_v1', 'cnpj',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=18),
               type_=sa.String(length=14),
               existing_nullable=True)
    op.alter_column('habitante_v1', 'cpf',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=14),
               type_=sa.String(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habitante_v1', 'cpf',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(collation='utf8_bin', length=14),
               existing_nullable=True)
    op.alter_column('empresa_v1', 'cnpj',
               existing_type=sa.String(length=14),
               type_=mysql.VARCHAR(collation='utf8_bin', length=18),
               existing_nullable=True)
    # ### end Alembic commands ###
