"""empty message

Revision ID: dc7d560eee94
Revises: fead50b08d21
Create Date: 2019-12-09 21:36:23.567152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7d560eee94'
down_revision = 'fead50b08d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa_v1', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa_v1', 'desc')
    # ### end Alembic commands ###
